export const FETCH_API_DATA_START = 'FETCH_API_DATA_START';
export const FETCH_API_DATA_SUCCESS = 'FETCH_API_DATA_SUCCESS';
export const FETCH_API_DATA_FAIL = 'FETCH_API_DATA_FAIL';
export const SEARCH_FOOD = 'SEARCH_FOOD';
